# Generated by Django 4.2.6 on 2023-11-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resto", "0003_rename_date_booking_booking_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="chefs_images/")),
                ("twitter_link", models.URLField(blank=True, null=True)),
                ("facebook_link", models.URLField(blank=True, null=True)),
                ("instagram_link", models.URLField(blank=True, null=True)),
                ("linkedin_link", models.URLField(blank=True, null=True)),
                ("bio", models.TextField()),
            ],
        ),
    ]
