# Generated by Django 4.2.6 on 2023-11-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resto", "0004_chef"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chef",
            name="image",
            field=models.ImageField(upload_to="chefs/"),
        ),
    ]
