# Generated by Django 4.2.6 on 2023-11-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resto", "0005_alter_chef_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="gallery/")),
            ],
        ),
    ]
